### ISSUE TITLE
개인 코드 수정

### ISSUE THREAD

**Issue by winnaba61** [winnaba61/virtual-invest#6]

**Comment by winnaba61** [comment]
차트구현완료, 전체디자인수정, 각종목에맞는주식정보불러오기

**Comment by hanejj** [comment]
회원가입 후, 해당 유저 아이디 DB 저장되도록 수정.
주식 가상 매매 시, 주식 검색 후, 각 주식 거래되도록 수정.
마이페이지 오류 수정.

**Comment by tlsdbstjr** [comment]
데이터 베이스에 필요한 table을 만들 수 있도록 migrations 파일 추가
account 페이지 입력시 예외처리 루틴 추가

**Comment by DwKwCs** [comment]
로그인 페이지에서 회원가입한 계정의 아이디와 비밀번호를 등록한 이메일로 찾을 수 있는 기능 추가
